### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by johannesdz** [robertgonzales/react-step-range-slider#2]
Hi, i run into following error, when i try to run the slider:
>> .../www/node_modules/react-step-range-slider/dist/StepRangeSlider.css:1
>> .StepRangeSlider {
>> ^
>> ParseError: Unexpected token
Does someone else experienced this problem? I also don't understand, why StepRangeSlider.js requires a .css file. I would prefer to separate my styles from code.
Thank you for your help!
Johannes

**Comment by robertgonzales** [comment]
This is an issue with your build process. It shouldn't be trying to parse the .css file. 

Are you using webpack? You may want to look at this: https://github.com/webpack/webpack/issues/1754

The only reason StepRangeSlider.js requires the .css file is so that your build process can load the default styles when you import the slider. This is the standard approach with webpack: https://webpack.github.io/docs/stylesheets.html
